### ISSUE TITLE
Can't add the bot to my Server

### ISSUE THREAD

**Issue by Squaishy** [LuisMayo/ace-attorney-discord-bot#1]
![Screenshot_20210218_220511](https://user-images.githubusercontent.com/74464309/108368488-79f71080-7235-11eb-90f7-40a65d721929.png)

This error pops up whenever I tried.

**Comment by LuisMayo** [comment]
Hi. Thanks for letting me know!

Ok I'll try to explain the problem (you can skip to the end). [Discord has a policy](https://support.discord.com/hc/en-us/articles/360040720412) in which they must manually review bots in order for them to join more than 100 servers:

> Therefore, we are making verification a requirement for bots in 100 or more servers. Until your bot is verified, you will not be able to grow past 100 servers. If your bot is already in more than 100 servers, it will not be able to join any more.

That being said, Discord sent me a message last Monday(15-Feb) stating that my bot had already being added to 75 servers. Meaning it was close to hitting the limit.
Following their instructions I filled the required form the following day (16-Feb). I've received no further communication from them since Tuesday. In the developer control panel it only states:
> Verification Request Processing
> We've received your request. We are reviewing your verification form and will reach out to you via email with more information.

**What to do?**
- I had the bot added to two testing servers myself, I just released it from one of the servers so it should be able to added to one more server now.
- Wait. It shouldn't take them long to verify it, it should be done in a few days. As long as they don't verify the bot there is little I can do except duplicating instances of it, which I won't do (I'm not sure they even allow it)
- You can host your own instance of the bot. I may help with this one if help is needed.

Regards.

**Comment by LuisMayo** [comment]
The bot has now been verified.
Thanks a lot for your patience
